export const sidebarLinks=[
    {
        label:'Home',
        route:'/',
        imageUrl:'/icons/Home.svg',
    },
    {
        label:'Upcoming',
        route:'/upcoming',
        imageUrl:'/icons/Upcoming.svg',
    },
    {
        label:'Previous',
        route:'/previous',
        imageUrl:'/icons/Previous.svg',
    },
    {
        label:'Recordings',
        route:'/recordings',
        imageUrl:'/icons/video.svg',
    },
    {
        label:'Personal-Room',
        route:'/personal-room',
        imageUrl:'/icons/add-personal.svg',
    },
]
export const avatarImages = [
    '/images/avatar-1.jpeg',
    '/images/avatar-2.jpeg',
    '/images/avatar-3.png',
    '/images/avatar-4.png',
    '/images/avatar-5.png',
  ];